"""empty message

Revision ID: 2431549ff93e
Revises: dbdc78c9c049
Create Date: 2022-08-21 02:35:16.625031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2431549ff93e'
down_revision = 'dbdc78c9c049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
