"""empty message

Revision ID: 3bb692a585f6
Revises: 2431549ff93e
Create Date: 2022-08-21 02:35:35.615160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb692a585f6'
down_revision = '2431549ff93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
