"""empty message

Revision ID: 57819bfda6eb
Revises: 3bb692a585f6
Create Date: 2022-08-21 02:35:48.576198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57819bfda6eb'
down_revision = '3bb692a585f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
