"""empty message

Revision ID: 763766030be5
Revises: a2dc12a28ce1
Create Date: 2022-08-21 12:28:07.148213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763766030be5'
down_revision = 'a2dc12a28ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
